/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugTaskadeRouteImport } from './routes/debug.taskade'
import { Route as DebugSubscriptionsRouteImport } from './routes/debug.subscriptions'
import { Route as DebugLeadsRouteImport } from './routes/debug.leads'
import { Route as DebugFictitiousRouteImport } from './routes/debug.fictitious'
import { Route as DebugEmailPreviewRouteImport } from './routes/debug.email-preview'
import { Route as DebugConfirmationEmailRouteImport } from './routes/debug.confirmation-email'
import { Route as DebugClassRemindersRouteImport } from './routes/debug.class-reminders'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsReconcileAccessRouteImport } from './routes/api/public/payments/reconcile-access'
import { Route as ApiPublicLeadsRecoverAbandonedRouteImport } from './routes/api/public/leads/recover-abandoned'
import { Route as ApiPublicHooksClassRemindersRouteImport } from './routes/api/public/hooks/class-reminders'
import { Route as ApiPublicHooksBillingRemindersRouteImport } from './routes/api/public/hooks/billing-reminders'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugTaskadeRoute = DebugTaskadeRouteImport.update({
  id: '/debug/taskade',
  path: '/debug/taskade',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSubscriptionsRoute = DebugSubscriptionsRouteImport.update({
  id: '/debug/subscriptions',
  path: '/debug/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLeadsRoute = DebugLeadsRouteImport.update({
  id: '/debug/leads',
  path: '/debug/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugFictitiousRoute = DebugFictitiousRouteImport.update({
  id: '/debug/fictitious',
  path: '/debug/fictitious',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEmailPreviewRoute = DebugEmailPreviewRouteImport.update({
  id: '/debug/email-preview',
  path: '/debug/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugConfirmationEmailRoute = DebugConfirmationEmailRouteImport.update({
  id: '/debug/confirmation-email',
  path: '/debug/confirmation-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugClassRemindersRoute = DebugClassRemindersRouteImport.update({
  id: '/debug/class-reminders',
  path: '/debug/class-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsReconcileAccessRoute =
  ApiPublicPaymentsReconcileAccessRouteImport.update({
    id: '/api/public/payments/reconcile-access',
    path: '/api/public/payments/reconcile-access',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsRecoverAbandonedRoute =
  ApiPublicLeadsRecoverAbandonedRouteImport.update({
    id: '/api/public/leads/recover-abandoned',
    path: '/api/public/leads/recover-abandoned',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksClassRemindersRoute =
  ApiPublicHooksClassRemindersRouteImport.update({
    id: '/api/public/hooks/class-reminders',
    path: '/api/public/hooks/class-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBillingRemindersRoute =
  ApiPublicHooksBillingRemindersRouteImport.update({
    id: '/api/public/hooks/billing-reminders',
    path: '/api/public/hooks/billing-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/debug/class-reminders': typeof DebugClassRemindersRoute
  '/debug/confirmation-email': typeof DebugConfirmationEmailRoute
  '/debug/email-preview': typeof DebugEmailPreviewRoute
  '/debug/fictitious': typeof DebugFictitiousRoute
  '/debug/leads': typeof DebugLeadsRoute
  '/debug/subscriptions': typeof DebugSubscriptionsRoute
  '/debug/taskade': typeof DebugTaskadeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/hooks/billing-reminders': typeof ApiPublicHooksBillingRemindersRoute
  '/api/public/hooks/class-reminders': typeof ApiPublicHooksClassRemindersRoute
  '/api/public/leads/recover-abandoned': typeof ApiPublicLeadsRecoverAbandonedRoute
  '/api/public/payments/reconcile-access': typeof ApiPublicPaymentsReconcileAccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/debug/class-reminders': typeof DebugClassRemindersRoute
  '/debug/confirmation-email': typeof DebugConfirmationEmailRoute
  '/debug/email-preview': typeof DebugEmailPreviewRoute
  '/debug/fictitious': typeof DebugFictitiousRoute
  '/debug/leads': typeof DebugLeadsRoute
  '/debug/subscriptions': typeof DebugSubscriptionsRoute
  '/debug/taskade': typeof DebugTaskadeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/hooks/billing-reminders': typeof ApiPublicHooksBillingRemindersRoute
  '/api/public/hooks/class-reminders': typeof ApiPublicHooksClassRemindersRoute
  '/api/public/leads/recover-abandoned': typeof ApiPublicLeadsRecoverAbandonedRoute
  '/api/public/payments/reconcile-access': typeof ApiPublicPaymentsReconcileAccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/debug/class-reminders': typeof DebugClassRemindersRoute
  '/debug/confirmation-email': typeof DebugConfirmationEmailRoute
  '/debug/email-preview': typeof DebugEmailPreviewRoute
  '/debug/fictitious': typeof DebugFictitiousRoute
  '/debug/leads': typeof DebugLeadsRoute
  '/debug/subscriptions': typeof DebugSubscriptionsRoute
  '/debug/taskade': typeof DebugTaskadeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/hooks/billing-reminders': typeof ApiPublicHooksBillingRemindersRoute
  '/api/public/hooks/class-reminders': typeof ApiPublicHooksClassRemindersRoute
  '/api/public/leads/recover-abandoned': typeof ApiPublicLeadsRecoverAbandonedRoute
  '/api/public/payments/reconcile-access': typeof ApiPublicPaymentsReconcileAccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/membership'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/checkout/return'
    | '/debug/class-reminders'
    | '/debug/confirmation-email'
    | '/debug/email-preview'
    | '/debug/fictitious'
    | '/debug/leads'
    | '/debug/subscriptions'
    | '/debug/taskade'
    | '/.lovable/oauth/consent'
    | '/api/public/hooks/billing-reminders'
    | '/api/public/hooks/class-reminders'
    | '/api/public/leads/recover-abandoned'
    | '/api/public/payments/reconcile-access'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/membership'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/checkout/return'
    | '/debug/class-reminders'
    | '/debug/confirmation-email'
    | '/debug/email-preview'
    | '/debug/fictitious'
    | '/debug/leads'
    | '/debug/subscriptions'
    | '/debug/taskade'
    | '/.lovable/oauth/consent'
    | '/api/public/hooks/billing-reminders'
    | '/api/public/hooks/class-reminders'
    | '/api/public/leads/recover-abandoned'
    | '/api/public/payments/reconcile-access'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mcp'
    | '/membership'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/checkout/return'
    | '/debug/class-reminders'
    | '/debug/confirmation-email'
    | '/debug/email-preview'
    | '/debug/fictitious'
    | '/debug/leads'
    | '/debug/subscriptions'
    | '/debug/taskade'
    | '/.lovable/oauth/consent'
    | '/api/public/hooks/billing-reminders'
    | '/api/public/hooks/class-reminders'
    | '/api/public/leads/recover-abandoned'
    | '/api/public/payments/reconcile-access'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DebugClassRemindersRoute: typeof DebugClassRemindersRoute
  DebugConfirmationEmailRoute: typeof DebugConfirmationEmailRoute
  DebugEmailPreviewRoute: typeof DebugEmailPreviewRoute
  DebugFictitiousRoute: typeof DebugFictitiousRoute
  DebugLeadsRoute: typeof DebugLeadsRoute
  DebugSubscriptionsRoute: typeof DebugSubscriptionsRoute
  DebugTaskadeRoute: typeof DebugTaskadeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicHooksBillingRemindersRoute: typeof ApiPublicHooksBillingRemindersRoute
  ApiPublicHooksClassRemindersRoute: typeof ApiPublicHooksClassRemindersRoute
  ApiPublicLeadsRecoverAbandonedRoute: typeof ApiPublicLeadsRecoverAbandonedRoute
  ApiPublicPaymentsReconcileAccessRoute: typeof ApiPublicPaymentsReconcileAccessRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/taskade': {
      id: '/debug/taskade'
      path: '/debug/taskade'
      fullPath: '/debug/taskade'
      preLoaderRoute: typeof DebugTaskadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/subscriptions': {
      id: '/debug/subscriptions'
      path: '/debug/subscriptions'
      fullPath: '/debug/subscriptions'
      preLoaderRoute: typeof DebugSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/leads': {
      id: '/debug/leads'
      path: '/debug/leads'
      fullPath: '/debug/leads'
      preLoaderRoute: typeof DebugLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/fictitious': {
      id: '/debug/fictitious'
      path: '/debug/fictitious'
      fullPath: '/debug/fictitious'
      preLoaderRoute: typeof DebugFictitiousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/email-preview': {
      id: '/debug/email-preview'
      path: '/debug/email-preview'
      fullPath: '/debug/email-preview'
      preLoaderRoute: typeof DebugEmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/confirmation-email': {
      id: '/debug/confirmation-email'
      path: '/debug/confirmation-email'
      fullPath: '/debug/confirmation-email'
      preLoaderRoute: typeof DebugConfirmationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/class-reminders': {
      id: '/debug/class-reminders'
      path: '/debug/class-reminders'
      fullPath: '/debug/class-reminders'
      preLoaderRoute: typeof DebugClassRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/reconcile-access': {
      id: '/api/public/payments/reconcile-access'
      path: '/api/public/payments/reconcile-access'
      fullPath: '/api/public/payments/reconcile-access'
      preLoaderRoute: typeof ApiPublicPaymentsReconcileAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/recover-abandoned': {
      id: '/api/public/leads/recover-abandoned'
      path: '/api/public/leads/recover-abandoned'
      fullPath: '/api/public/leads/recover-abandoned'
      preLoaderRoute: typeof ApiPublicLeadsRecoverAbandonedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/class-reminders': {
      id: '/api/public/hooks/class-reminders'
      path: '/api/public/hooks/class-reminders'
      fullPath: '/api/public/hooks/class-reminders'
      preLoaderRoute: typeof ApiPublicHooksClassRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/billing-reminders': {
      id: '/api/public/hooks/billing-reminders'
      path: '/api/public/hooks/billing-reminders'
      fullPath: '/api/public/hooks/billing-reminders'
      preLoaderRoute: typeof ApiPublicHooksBillingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  MembershipRoute: MembershipRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DebugClassRemindersRoute: DebugClassRemindersRoute,
  DebugConfirmationEmailRoute: DebugConfirmationEmailRoute,
  DebugEmailPreviewRoute: DebugEmailPreviewRoute,
  DebugFictitiousRoute: DebugFictitiousRoute,
  DebugLeadsRoute: DebugLeadsRoute,
  DebugSubscriptionsRoute: DebugSubscriptionsRoute,
  DebugTaskadeRoute: DebugTaskadeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicHooksBillingRemindersRoute: ApiPublicHooksBillingRemindersRoute,
  ApiPublicHooksClassRemindersRoute: ApiPublicHooksClassRemindersRoute,
  ApiPublicLeadsRecoverAbandonedRoute: ApiPublicLeadsRecoverAbandonedRoute,
  ApiPublicPaymentsReconcileAccessRoute: ApiPublicPaymentsReconcileAccessRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
